package br.univel.testes;

public class TestandoLista {
	
	public static void main(String[] args) {
		System.out.println(DADOS.toString());
	}
	public static final String[] DADOS = new String[] {
			"# 12 faixas",
			"Hardwired",
			"Atlas, Rise!",
			"Now That We're Dead",
			"Moth Into Flame",
			"Dream No More",
			"Halo On Fire",
			"Confusion",
			"ManUNkind",
			"Here Comes Revenge",
			"Am I Savage?",
			"Murder One",
			"Spit Out The Bone",
			"Through the NeverPLAYThrough the Never",
			"2013",
			"Blackened Recordings",
			"# 8 faixas",
			"The Ecstasy Of Gold",
			"Creeping Death",
			"For Whom The Bell Tolls",
			"Fuel",
			"Ride The Lightning",
			"One",
			"The Memory Remains",
			"Wherever I May Roam",
			"# 8 faixas",
			"Cyanide",
			"...And Justice For All",
			"Master Of Puppets",
			"Battery",
			"Nothing Else Matters",
			"tocou há 2h",
			"SimKast Radio | Tune In...Get Connected",
			"Enter Sandman",
			"Hit The Lights",
			"Orion",
			"Beyond Magnetic (EP)PLAYBeyond Magnetic (EP)",
			"2011",
			"Mercury",
			"# 4 faixas",
			"Hate Train",
			"Just a Bullet Away",
			"Hell and Back",
			"Rebel Of Babylon",
			"Lulu (Colaboration with Lou Reed)PLAYLulu (Colaboration with Lou Reed)",
			"2011",
			"Warner Bros.; Vertigo",
			"# 6 faixas",
			"Brandenburg Gate (with Lou Reed)",
			"The View (with Lou Reed)",
			"Pumping Blood (with Lou Reed)",
			"Mistress Dread (with Lou Reed)",
			"Iced Honey (with Lou Reed)",
			"Cheat On Me (with Lou Reed)",
			"# 4 faixas",
			"Frustration (with Lou Reed)",
			"Little Dog (feat. Lou Reed)",
			"Dragon (with Lou Reed)",
			"Junior Dad (with Lou Reed)",
			"Death MagneticPLAYDeath Magnetic",
			"2008",
			"Warner Bros.",
			"# 10 faixas",
			"That Was Just Your Life",
			"The End Of The Line",
			"Broken, Beat & Scarred",
			"The Day That Never Comes",
			"All Nightmare Long",
			"Cyanide",
			"The Unforgiven III",
			"The Judas Kiss",
			"Suicide & Redemption",
			"My Apocalypse",
			"Some Kind of MonsterPLAYSome Kind of Monster",
			"2004",
			"Warner Bros / Wea",
			"# 8 faixas",
			"Some Kind of Monster",
			"The Four Horsemen - Live - Paris",
			"Damage Inc. - Live - Paris",
			"Leper Messiah - Live - Paris",
			"Motorbreath - Live - Paris",
			"Ride the Lightning - Live-w/Intro - Paris",
			"Hit the Lights - Live - Paris",
			"Some Kind of Monster - Edit",
			"St. AngerPLAYSt. Anger",
			"2003",
			"# 11 faixas",
			"Frantic",
			"St. Anger",
			"Some Kind Of Monster",
			"Dirty Window",
			"Invisible Kid",
			"My World",
			"Shoot Me Again",
			"Sweet Amber",
			"The Unnamed Feeling",
			"Purify",
			"All Within My Hands",
			"S&MPLAYS&M",
			"1999",
			"Elektra / Wea",
			"# 11 faixas",
			"The Ecstasy Of Gold",
			"The Call Of The Ktul",
			"Master Of Puppets",
			"Of Wolf And Man",
			"The Thing That Should Not Be",
			"Fuel",
			"The Memory Remains",
			"No Leaf Clover",
			"Hero Of The Day",
			"Devil's Dance",
			"Bleeding Me",
			"# 10 faixas",
			"Nothing Else Matters",
			"tocou há 2h",
			"SimKast Radio | Tune In...Get Connected",
			"Until It Sleeps",
			"For Whom The Bell Tolls",
			"Human",
			"Wherever I May Roam",
			"Outlaw Torn",
			"Sad But True",
			"One",
			"Enter Sandman",
			"Battery",
			"Garage Inc.PLAYGarage Inc.",
			"1998",
			"Elektra / Wea",
			"# 11 faixas",
			"Free Speech For The Dumb",
			"It`s Electric",
			"Sabbra Cadabra",
			"Turn The Page",
			"Die, Die My Darling",
			"Loverman",
			"Mercyful Fate",
			"Astronomy",
			"Whiskey In The Jar",
			"Tuesday`s Gone",
			"The More I See",
			"# 16 faixas",
			"Helpless",
			"The Small Hours",
			"The Wait",
			"Crash Course In Brain Surgery",
			"Last Caress/green Hell",
			"Am I Evil?",
			"Blitzkrieg",
			"Breadfan",
			"The Prince",
			"Stone Cold Crazy",
			"So What",
			"Killing Time",
			"Overkill",
			"Damage Case",
			"Stone Dead Forever",
			"Too Late Too Late",
			"ReloadPLAYReload",
			"1997",
			"Elektra / Wea",
			"# 13 faixas",
			"FUEL",
			"THE MEMORY REMAINS",
			"DEVIL'S DANCE",
			"THE UNFORGIVEN II",
			"BETTER THAN YOU",
			"SLITHER",
			"CARPE DIEM BABY",
			"BAD SEED",
			"WHERE THE WILD THINGS ARE",
			"PRINCE CHARMING",
			"LOW MAN'S LYRIC",
			"ATTITUDE",
			"FIXXXER",
			"LoadPLAYLoad",
			"1996",
			"Elektra / Wea",
			"# 14 faixas",
			"AIN'T MY BITCH",
			"2 X 4",
			"THE HOUSE JACK BUILT",
			"UNTIL IT SLEEPS",
			"KING NOTHING",
			"HERO OF THE DAY",
			"BLEEDING ME",
			"CURE",
			"POOR TWISTED ME",
			"WASTING MY HATE",
			"MAMA SAID",
			"THORN WITHIN",
			"RONNIE",
			"THE OUTLAW TORN",
			"1993",
			"Universal",
			"# 8 faixas",
			"Enter Sandman - CD",
			"Creeping Death - CD",
			"Harvester Of Sorrow - CD",
			"Welcome Home (Sanitarium) - CD",
			"Sad But True - CD",
			"Of Wolf And Man - CD",
			"The Unforgiven - CD",
			"Justice Medley - CD",
			"# 6 faixas",
			"Trough The Never - CD",
			"For Whom The Bell Tolls - CD",
			"Fade To Black - CD",
			"Master Of Puppets - CD",
			"Seek & Destroy - CD",
			"tocou há 2h",
			"Rádio D.K",
			"Whiplash - CD",
			"# 9 faixas",
			"Nothing Else Matters - CD",
			"tocou há 2h",
			"SimKast Radio | Tune In...Get Connected",
			"Wherever I May Roam - CD",
			"Am I Evil? - CD",
			"Last CAress - CD",
			"One - CD",
			"Battery - CD",
			"The Four Horsemen - CD",
			"Motorbreath - CD",
			"Stone Cold Crazy - CD",
			"# 20 faixas",
			"Enter Sandman - DVD",
			"Creeping Death - DVD",
			"Harvester Of Sorrow - DVD",
			"Welcome Home (Sanitarium) - DVD",
			"Sad But True - DVD",
			"Wherever I May Roam - DVD",
			"Trough The Never - DVD",
			"The Unforgiven - DVD",
			"Justice Medley - DVD",
			"The Four Horsemen - DVD",
			"For Whom The Bell Tolls - DVD",
			"Fade To Black - DVD",
			"Whiplash - DVD",
			"Master Of Puppets - DVD",
			"Seek & Destroy - DVD",
			"tocou há 2h",
			"Rádio D.K",
			"One - DVD",
			"Last Caress - DVD",
			"Am I Evil? - DVD",
			"Battery - DVD",
			"Stone Cold Crazy - DVD",
			"# 12 faixas",
			"Blackened - DVD",
			"For Whom The Bell Tolls - DVD",
			"Welcome Home (Sanitarium) - DVD",
			"Harvester Of Sorrow - DVD",
			"The Four Horsemen - DVD",
			"The Thing That Should Not Be - DVD",
			"Master Of Puppets - DVD",
			"Fade To Black - DVD",
			"Seek & Destroy - DVD",
			"tocou há 2h",
			"Rádio D.K",
			"...And Justice For All - DVD",
			"One - DVD",
			"Creeping Death - DVD",
			"Metallica (Black Album)PLAYMetallica (Black Album)",
			"1991",
			"Elektra / Wea",
			"# 12 faixas",
			"Enter Sandman",
			"Sad But True",
			"Holier Than Thou",
			"The Unforgiven",
			"Wherever I May Roam",
			"Don t Tread On Me",
			"Through The Never",
			"Nothing Else Matters",
			"tocou há 2h",
			"SimKast Radio | Tune In...Get Connected",
			"Of Wolf And Man",
			"The God That Failed",
			"My Friend Of Misery",
			"The Struggle Within",
			"And Justice for AllPLAYAnd Justice for All",
			"1988",
			"Elektra / Wea",
			"# 9 faixas",
			"Blackened",
			"...and Justice For All",
			"Eye Of The Beholder",
			"One",
			"The Shortest Straw",
			"Harvester Of Sorrow",
			"The Frayed Ends Of Sanity",
			"To Live Is to Die",
			"Dyers Eve",
			"Master of PuppetsPLAYMaster of Puppets",
			"1986",
			"Elektra / Wea",
			"# 8 faixas",
			"Battery",
			"Master Of Puppets",
			"The Thing That Should Not Be",
			"Welcome Home (Sanitarium)",
			"Disposable Heroes",
			"Leper Messiah",
			"Orion",
			"Damage, Inc",
			"Ride the LightningPLAYRide the Lightning",
			"1984",
			"Elektra / Wea",
			"# 8 faixas",
			"Fight Fire With Fire",
			"Ride The Lightning",
			"For Whom The Bell Tolls",
			"Fade To Black",
			"Trapped Under Ice",
			"Escape",
			"Creeping Death",
			"The Call Of ktulu",
			"Kill 'Em AllPLAYKill 'Em All",
			"1983",
			"Universal Music",
			"# 10 faixas",
			"Hit The Lights",
			"The Four Horsemen",
			"Motorbreath",
			"Jump In The Fire",
			"(anesthesia)-pulling Teeth - Metallica",
			"Whiplash",
			"Phantom Lord",
			"No Remorse",
			"Seek & Destroy",
			"tocou há 2h",
			"Rádio D.K",
			"Metal Militia"	
	};
}
